export const jobDetail = [
  {
    title: "Product Designer",
    description: "We’re Looking for a mid-level designer to join our team",
    department: "Design",
    tags: ["100% Remote", "Full-Time"],
    tasks: [
      "Reception, diagnosis and treatment of animals with cardiological diseases",
      "Conducting ECHOKG, ECG, dopplerography, preoperative heart screenshots; interpretation of research results",
      "Study of the causes of occurrence, the processes of the disease",
      "Development of treatment methods",
      "The use of medicines",
    ],
    terms: [
      "Reception, diagnosis and treatment of animals with cardiological diseases",
      "Conducting ECHOKG, ECG, dopplerography, preoperative heart screenshots; interpretation of research results",
      "Study of the causes of occurrence, the processes of the disease",
      "Development of treatment methods",
      "The use of medicines",
    ],
    expectations: [
      "Reception, diagnosis and treatment of animals with cardiological diseases",
      "Conducting ECHOKG, ECG, dopplerography, preoperative heart screenshots; interpretation of research results",
      "Study of the causes of occurrence, the processes of the disease",
      "Development of treatment methods",
      "The use of medicines",
    ],
  },
  {
    title: "Frontend Developer",
    description: "We’re Looking for a mid-level designer to join our team",
    department: "Development",
    tags: ["Remote", "Full-Time", "hybrid"],
    tasks: [
      "Reception, diagnosis and treatment of animals with cardiological diseases",
      "Conducting ECHOKG, ECG, dopplerography, preoperative heart screenshots; interpretation of research results",
      "Study of the causes of occurrence, the processes of the disease",
      "Development of treatment methods",
      "The use of medicines",
    ],
    terms: [
      "Reception, diagnosis and treatment of animals with cardiological diseases",
      "Conducting ECHOKG, ECG, dopplerography, preoperative heart screenshots; interpretation of research results",
      "Study of the causes of occurrence, the processes of the disease",
      "Development of treatment methods",
      "The use of medicines",
    ],
    expectations: [
      "Reception, diagnosis and treatment of animals with cardiological diseases",
      "Conducting ECHOKG, ECG, dopplerography, preoperative heart screenshots; interpretation of research results",
      "Study of the causes of occurrence, the processes of the disease",
      "Development of treatment methods",
      "The use of medicines",
    ],
  },
  {
    title: "Client Relation Executive",
    description: "We’re Looking for a mid-level designer to join our team",
    department: "Customer Service",
    tags: ["Full-Time"],
    tasks: [
      "Reception, diagnosis and treatment of animals with cardiological diseases",
      "Conducting ECHOKG, ECG, dopplerography, preoperative heart screenshots; interpretation of research results",
      "Study of the causes of occurrence, the processes of the disease",
      "Development of treatment methods",
      "The use of medicines",
    ],
    terms: [
      "Reception, diagnosis and treatment of animals with cardiological diseases",
      "Conducting ECHOKG, ECG, dopplerography, preoperative heart screenshots; interpretation of research results",
      "Study of the causes of occurrence, the processes of the disease",
      "Development of treatment methods",
      "The use of medicines",
    ],
    expectations: [
      "Reception, diagnosis and treatment of animals with cardiological diseases",
      "Conducting ECHOKG, ECG, dopplerography, preoperative heart screenshots; interpretation of research results",
      "Study of the causes of occurrence, the processes of the disease",
      "Development of treatment methods",
      "The use of medicines",
    ],
  },
];
